name: Update README.md
on:
  schedule:
    - cron: "0 15 * * *" # JST 0AM
  workflow_dispatch:
  pull_request:
    paths:
      - .github/workflows/update-readme.yml

jobs:
  update_readmemd:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    env:
      GITHUB_TOKEN: ${{ secrets.TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - run: go install github.com/nasustim/ghsummarygen@latest
      - name: Make summary
        run: |
          ghsummarygen --user_name nasustim --access_token $GITHUB_TOKEN --out ./github-stat.svg

          if [ ! -e ./images ]; then
            mkdir images
          fi
          mv ./github-stat.svg ./images/
      - name: Generate README.md
        run: go run cmd/cli/main.go
      - name: Push to main
        if: github.event_name != 'pull_request'
        run: |
          # diffがない場合はskip
          has_diff=$(git status | grep 'Changes not staged for commit' || true)
          if [ -z "${has_diff}" ]; then
            exit 0
          fi

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[auto commit] update README.md"
          git push origin main
