name: Update README.md
on:
  pull_request:

jobs:
  update_readmemd:
    runs-on: ubuntu-latest
    timeout-minutes: 3 # 仮
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - run: go run cmd/cli/main.go
      - run: |
          # diffがない場合はskip
          has_diff=$(git status | grep 'Changes not staged for commit')
          if [ -z "${has_diff}" ]; then
            exit 0
          fi

          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[auto commit] update README.md"
          git push origin HEAD
